// Code generated by Kitex v0.12.3. DO NOT EDIT.

package userservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	user "wiliwili/kitex_gen/user"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UserRegister(ctx context.Context, req *user.UserRegisterReq, callOptions ...callopt.Option) (r *user.UserRegisterResp, err error)
	UserLogin(ctx context.Context, req *user.UserLoginReq, callOptions ...callopt.Option) (r *user.UserLoginResp, err error)
	UserProfile(ctx context.Context, req *user.UserProfileReq, callOptions ...callopt.Option) (r *user.UserProfileResp, err error)
	UserAvatarUpload(ctx context.Context, req *user.UserAvatarUploadReq, callOptions ...callopt.Option) (r *user.UserAvatarUploadResp, err error)
	UserAvatarGet(ctx context.Context, req *user.UserAvatarGetReq, callOptions ...callopt.Option) (r *user.UserAvatarGetResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kUserServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kUserServiceClient struct {
	*kClient
}

func (p *kUserServiceClient) UserRegister(ctx context.Context, req *user.UserRegisterReq, callOptions ...callopt.Option) (r *user.UserRegisterResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserRegister(ctx, req)
}

func (p *kUserServiceClient) UserLogin(ctx context.Context, req *user.UserLoginReq, callOptions ...callopt.Option) (r *user.UserLoginResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserLogin(ctx, req)
}

func (p *kUserServiceClient) UserProfile(ctx context.Context, req *user.UserProfileReq, callOptions ...callopt.Option) (r *user.UserProfileResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserProfile(ctx, req)
}

func (p *kUserServiceClient) UserAvatarUpload(ctx context.Context, req *user.UserAvatarUploadReq, callOptions ...callopt.Option) (r *user.UserAvatarUploadResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserAvatarUpload(ctx, req)
}

func (p *kUserServiceClient) UserAvatarGet(ctx context.Context, req *user.UserAvatarGetReq, callOptions ...callopt.Option) (r *user.UserAvatarGetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UserAvatarGet(ctx, req)
}
