// Code generated by hertz generator.

package video

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	video "wiliwili/app/gateway/model/api/video"
)

// SubmitVideo .
// @router api/v1/video/submit [POST]
func SubmitVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoSubmissionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoSubmissionResp)

	c.JSON(consts.StatusOK, resp)
}

// GetVideo .
// @router api/v1/video/get [GET]
func GetVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoGetReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoGetResp)

	c.JSON(consts.StatusOK, resp)
}

// SearchVideo .
// @router api/v1/video/search [GET]
func SearchVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoSearchReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoSearchResp)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoTrending .
// @router api/v1/video/trending [GET]
func GetVideoTrending(ctx context.Context, c *app.RequestContext) {
	var err error
	var req video.VideoTrendingReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(video.VideoTrendingResp)

	c.JSON(consts.StatusOK, resp)
}
