// Code generated by hertz generator.

package comment

import (
	"wiliwili/app/gateway/mw"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	mw.SentinelServer()
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _replycommentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mw.Auth(),
	}
}

func _getcommentreplylistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentvideoMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
	}
}

func _deletecommentMw() []app.HandlerFunc {
	return []app.HandlerFunc{
		mw.Auth(),
	}
}

func _getvideocommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
