// Code generated by hertz generator.

package chat

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	chat "wiliwili/app/gateway/model/api/chat"
)

// Chat .
// @router api/v1/chat [GET]
func Chat(ctx context.Context, c *app.RequestContext) {
	var err error
	var req chat.ChatReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(chat.ChatResp)

	c.JSON(consts.StatusOK, resp)
}
