version: '3.8'

services:
  wiliwili-redis:
    container_name: wiliwili-redis
    image: redis:bookworm
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    env_file:
      - "./env/redis.env"
    networks:
      - wiliwili

  wiliwili-mysql:
    container_name: wiliwili-mysql
    image: mysql:9.0.1
    ports:
      - "3306:3306"
    env_file:
      - "./env/mysql.env"
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    networks:
      - wiliwili
   # etcd 服务，分布式键值存储系统，用于服务发现、配置管理
  wiliwili-etcd:
    container_name: wiliwili-etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - "./env/etcd.env"
    volumes:
      - ./script:/script
      - ../config:/config
      - ./data/etcd:/etcd-data
    networks:
      - wiliwili
    entrypoint: [ "sh", "-c", "chmod +x /script/etcd-monitor.sh && /script/etcd-monitor.sh & exec etcd" ]


volumes:
  wiliwili-redis-data:
  wiliwili-mysql-data:

networks:
  wiliwili:
    driver: bridge  # 默认使用桥接网络