services:
  # Redis 服务，用于缓存、会话管理等，提供键值存储功能
  wiliwili-redis:
    container_name: wiliwili-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - wiliwili-redis-data:/data
    env_file:
      - "./env/redis.env"
    networks:
      - wiliwili

  # MySQL 服务，提供关系型数据库，用于存储结构化数据
  wiliwili-mysql:
  container_name: wiliwili-mysql
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    -../config/sql:/docker-entrypoint-initdb.d
    - wiliwili-mysql-data:/var/lib/mysql
  networks:
    - wiliwili

   # etcd 服务，分布式键值存储系统，用于服务发现、配置管理
  domtok-etcd:
    container_name: wiliwili-etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - "./env/etcd.env"
    volumes:
      - ./script:/script
      - ../config:/config
      - ./data/etcd:/etcd-data
    networks:
      - wiliwili
    entrypoint: [ "sh", "-c", "chmod +x /script/etcd-monitor.sh && /script/etcd-monitor.sh & exec etcd" ]
