services:
  wiliwili-redis:
    container_name: wiliwili-redis
    image: redis:bookworm
    volumes:
      - wiliwili-redis-data:/data
    ports:
      - "6379:6379"
    env_file:
      - "./env/redis.env"
    networks:
      - wiliwili

  wiliwili_mysql:
    image: mysql:8.0
    container_name: wiliwili-mysql
    restart: always
    env_file:
      - "./env/mysql.env"
    ports:
      - "3306:3306"
    networks:
      - wiliwili
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - wiliwili-mysql-data:/var/lib/mysql
   # etcd 服务，分布式键值存储系统，用于服务发现、配置管理
  wiliwili-etcd:
    container_name: wiliwili-etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - "./env/etcd.env"
    volumes:
      - ./script:/script
      - ../config:/config
      - wiliwili-etcd-data:/etcd-data
    networks:
      - wiliwili
    entrypoint: [ "sh", "-c", "chmod +x /script/etcd-monitor.sh && /script/etcd-monitor.sh & exec etcd" ]


volumes:
  wiliwili-etcd-data:
  wiliwili-redis-data:
  wiliwili-mysql-data:

networks:
  wiliwili:
    driver: bridge  # 默认使用桥接网络
    name: wiliwili