services:
  wiliwili-redis:
    container_name: wiliwili-redis
    image: redis:bookworm
    volumes:
       - ./data/redis-data:/data
    ports:
      - "6379:6379"
    env_file:
      - "./env/redis.env"
    networks:
      - wiliwili

  wiliwili_mysql:
    image: mysql:8.0
    container_name: wiliwili-mysql
    restart: always
    env_file:
      - "./env/mysql.env"
    ports:
      - "3306:3306"
    networks:
      - wiliwili
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
   # etcd 服务，分布式键值存储系统，用于服务发现、配置管理
  wiliwili-etcd:
    container_name: wiliwili-etcd
    image: quay.io/coreos/etcd:v3.5.5
    restart: always
    ports:
      - 2379:2379
      - 2380:2380
    env_file:
      - "./env/etcd.env"
    volumes:
      - ./script:/script
      - ../config:/config
    networks:
      - wiliwili
    entrypoint: [ "sh", "-c", "chmod +x /script/etcd-monitor.sh && /script/etcd-monitor.sh & exec etcd" ]

  wiliwili-minio:
    container_name: wiliwili-minio
    image: quay.io/minio/minio:latest
    ports:
    - "9000:9000"
    - "9001:9001"  # 添加控制台端口
    env_file:
    - ./env/minio.env
    volumes:
    - ./data/minio-data:/data
    networks:
    - wiliwili
    command: server /data --console-address ":9000" --address ":9001"

networks:
  wiliwili:
    driver: bridge  # 默认使用桥接网络
    name: wiliwili