version: '3.8'

services:
  wiliwili-redis:
    container_name: wiliwili-redis
    image: redis:bookworm
    ports:
      - "6379:6379"
    volumes:
      - wiliwili-redis-data:/data
    networks:
      - wiliwili

  wiliwili-mysql:
    container_name: wiliwili-mysql
    image: mysql:9.0.1
    ports:
      - "3306:3306"
    volumes:
      - ../config/sql:/docker-entrypoint-initdb.d
      - wiliwili-mysql-data:/var/lib/mysql
    networks:
      - wiliwili

volumes:
  wiliwili-redis-data:
  wiliwili-mysql-data:

networks:
  wiliwili:
    driver: bridge  # 默认使用桥接网络