// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	context "context"
	model "wiliwili/app/comment/domain/model"

	mock "github.com/stretchr/testify/mock"
)

// CommentCache is an autogenerated mock type for the CommentCache type
type CommentCache struct {
	mock.Mock
}

// DelCommentCache provides a mock function with given fields: ctx, id
func (_m *CommentCache) DelCommentCache(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DelCommentCache")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCommentList provides a mock function with given fields: ctx, id, page, pageSize, commenttype
func (_m *CommentCache) GetCommentList(ctx context.Context, id string, page int64, pageSize int64, commenttype int64) ([]*model.Comment, error) {
	ret := _m.Called(ctx, id, page, pageSize, commenttype)

	if len(ret) == 0 {
		panic("no return value specified for GetCommentList")
	}

	var r0 []*model.Comment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, int64) ([]*model.Comment, error)); ok {
		return rf(ctx, id, page, pageSize, commenttype)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64, int64) []*model.Comment); ok {
		r0 = rf(ctx, id, page, pageSize, commenttype)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Comment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64, int64) error); ok {
		r1 = rf(ctx, id, page, pageSize, commenttype)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetCommentList provides a mock function with given fields: ctx, id, commenttype, models
func (_m *CommentCache) SetCommentList(ctx context.Context, id string, commenttype int64, models []*model.Comment) error {
	ret := _m.Called(ctx, id, commenttype, models)

	if len(ret) == 0 {
		panic("no return value specified for SetCommentList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, []*model.Comment) error); ok {
		r0 = rf(ctx, id, commenttype, models)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommentCache creates a new instance of CommentCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommentCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *CommentCache {
	mock := &CommentCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
