// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	api_interactive "wiliwili/app/gateway/router/api/interactive"
	api_user "wiliwili/app/gateway/router/api/user"
	api_video "wiliwili/app/gateway/router/api/video"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	api_interactive.Register(r)

	api_video.Register(r)

	api_user.Register(r)
}
