// Code generated by hertz generator.

package like

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	like "wiliwili/app/gateway/model/api/like"
)

// LikeComment .
// @router api/v1/like/likecomment [POST]
func LikeComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req like.LikeCommentReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(like.LikeCommentResp)

	c.JSON(consts.StatusOK, resp)
}

// LikeVideo .
// @router api/v1/like/likevideo [POST]
func LikeVideo(ctx context.Context, c *app.RequestContext) {
	var err error
	var req like.LikeVideoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(like.LikeVideoResp)

	c.JSON(consts.StatusOK, resp)
}

// GetCommentLikeNum .
// @router api/v1/like/commentlike [GET]
func GetCommentLikeNum(ctx context.Context, c *app.RequestContext) {
	var err error
	var req like.CommentLikeNumReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(like.CommentLikeNumResp)

	c.JSON(consts.StatusOK, resp)
}

// GetVideoLikeNum .
// @router api/v1/like/videolike [GET]
func GetVideoLikeNum(ctx context.Context, c *app.RequestContext) {
	var err error
	var req like.VideoLikeNumReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(like.VideoLikeNumResp)

	c.JSON(consts.StatusOK, resp)
}
